version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  web:
    image: nginx:1.23-alpine3.17-slim
    volumes:
      - ./production:/etc/nginx/conf.d
    links:
      - app
    ports:
      - "8080:80"
  app:
    build:
      context: .
    environment:
      FLASK_ENV: prod
      SPOTIFY_REDIRECT_URI: "https://playlists.pygillier.me"
volumes:
  cache:
    driver: local