version: "3.8"

services:
  web:
    image: nginx:1.23-alpine3.17-slim
    volumes:
      - ./production:/etc/nginx/conf.d
    ports:
      - "8081:80"
    links:
      - app
  app:
    build:
      context: .
    environment:
      FLASK_ENV: prod
      SPOTIFY_REDIRECT_URI: "http://localhost:8081/oauth_dance"
    ports:
      - "8000:8000"