version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  web:
    build:
      context: nginx
    ports:
      - '80'
  app:
    build:
      context: .
    environment:
      FLASK_ENV: prod
      SPOTIFY_REDIRECT_URI: "https://playlists.pygillier.me"
volumes:
  cache:
    driver: local